    type: systemd
    system:
      enabled:
        - greetd
        - ananicy-cpp
        - scx
    user:
      enabled:
        - elephant

    type: files
    files:
      - source: system
        destination: /